"""Add passive income fields

Revision ID: 15af361d4d9d
Revises: 7bb35eb10050
Create Date: 2025-05-05 21:55:43.718873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af361d4d9d'
down_revision = '7bb35eb10050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_per_second', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cps_upgrades', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cps_upgrade_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_save', schema=None) as batch_op:
        batch_op.drop_column('cps_upgrade_price')
        batch_op.drop_column('cps_upgrades')
        batch_op.drop_column('coins_per_second')

    # ### end Alembic commands ###
