"""initial

Revision ID: 7bb35eb10050
Revises: 
Create Date: 2025-05-05 15:33:25.615582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb35eb10050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('monster_health', sa.Integer(), nullable=True),
    sa.Column('damage_upgrade_price', sa.Integer(), nullable=True),
    sa.Column('damage_upgrades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_save')
    # ### end Alembic commands ###
